#!/bin/bash

### mmcal by https://github.com/yan9a/mmcal
## This program displays with Zenity KDIALOG and NOTIFY SEND
## Maintain by kokoye2007

## Variables
NS=$(which notify-send 2>/dev/null)
KDIALOG=$(which kdialog 2>/dev/null) || KDIALOG=''
ZENITY=$(which zenity 2>/dev/null) || ZENITY=''

## Functions ##

#Function usage: displays help message in terminal or X
usage ()
{
MSG='This script prints of the 
Myanmar Calendar to notify-send 
if running X.

Options:
-g | gnome clander icon
-c | clander icon
-l | lotus icon

-h | --help     # Help

-s | --sasana   # Sasana Year
-b | --burmese  # Burmese Year
-y | --year     # Burmese Year Name
-n | --naga     # naga facing
-m | --mahabote # naga facing

-k | use kdialog
-z | use zenity'

if [ -z "$DISPLAY" ]; then
    echo -e '\e[0;31m'"\n${MSG}";echo -e '\e[0m' ""
    exit 0
elif [ -x "$ZENITY" ]; then
    $ZENITY --icon-name="mmcal" --info --title "Myanmar Calendar" --text "$MSG" --width=300 &>/dev/null
    exit 0
elif [ -x "$KDIALOG" ]; then
    $KDIALOG --msgbox "$MSG" &>/dev/null
    exit 0
else
    "$NS" -t 12000 "xdp options" "${MSG}" -i /usr/share/icons/mmcal.png
    exit 0
fi
}

# Function opts - get command line options
opts ()
{
case $OPT in
g | -g | --gnome) # gnome clander icon
ICON='gcalendar'
;;
c | -c | --calendar) # clander icon
ICON='mmcal'
;;
l | -l | --lotus) # lotus icon
ICON='lotus'
;;
h | -h | --help) # Help 
OPTION='h'
;;
s | -s | --sasana) # Sasana Year
OPTION='s'
;;
b | -b | --burmese) # Burmese Year
OPTION='b'
;;
y | -y | --year) # Burmese Year Name
OPTION='y'
;;
n | -n | --naga) # Naga Head / Facing
OPTION='n'
;;
m | -m | --mahabote) # Mahabote
OPTION='m'
;;
k | -k | --kdialog)
DIALOG=kdialog
;;
z | -z | --zenity)
DIALOG=zenity
;;
*)
usage
exit 1
;;
esac
}

## Main program ##


# Set default icon here
ICON='mmcal'

# Default is to call mmcal with out options, thus OPTION=''
OPTION=''

# By default we use notify-send
DIALOG=''

# Get options
# Get options
while [ "$#" -gt "0" ]
do
#if [[ "$1" =~ ^[0-9]+$ ]] ; then
#    VERSE="$1"
#fi
if [ "${1:0:2}" = "--" ] ; then
OPT="$1"
opts
else
while getopts "gclsbmnykzh" OPT; do
opts
done
fi
shift
done


# Get to be displayed
case $OPTION in
s)
MMCAL="`mmcal | sed '4!d;'`"
ICON=lotus
;;
b)
MMCAL="`mmcal | sed '2,3!d;'`"
;;
y)
MMCAL="`mmcal | sed '5!d;'`"
;;
n)
MMCAL="`mmcal | awk '/Naga facing/{print}'`"
;;
m)
MMCAL="`mmcal | awk  '/Mahabote/{print}'`"
;;
*)
MMCAL="`mmcal`"
;;
esac

# Check if we are running X
# If not, display a terminal
# If so, use notify-send
if [ -z "$DISPLAY" ]; then
    echo -e '\e[0;32m'"$MMCAL";echo -e '\e[0m' ""
elif [ -z "$DIALOG" ]; then
    if [ "$OPTION" == h ]; then 
	    usage 
    elif [ -x "$NS" ]; then
        "$NS" -t 16000 "Myanmar Calendar" "$MMCAL" -i "${ICON}" &>/dev/null || echo -e '\e[0;31m' "notify-send failed";echo -e '\e[0m' ""
    else
        echo -e '\e[0;31m' "Please install libnotify";echo -e '\e[0m' ""
    exit 0
    fi
else
    case $DIALOG in
    kdialog)
        if [ ! -z "$KDIALOG" ]; then
            $KDIALOG --title "Myanmar Calendar" --msgbox "$MMCAL" &>/dev/null
        else
            "$NS" -t 16000 "Myanmar Calendar" "$MMCAL" -i "${ICON}" &>/dev/null
        fi
        exit 0
    ;;
    zenity)
        if [ ! -z "$ZENITY" ]; then
            $ZENITY --info --title="Myanmar Calendar" --text="${MMCAL}" --icon-name="${ICON}" --width=300  &>/dev/null
        else
            "$NS" -t 16000 "Myanmar Calendar" "$MMCAL" -i "${ICON}" &>/dev/null
        fi
        exit 0
    ;;
    esac
fi

exit 0
