#!/bin/sh
set -e
# Automatically added by dh_icons/12.6.1ubuntu2
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/gcalendar.png /usr/share/icons/lotus.png /usr/share/icons/mmcal.png
fi
# End automatically added section
